### ISSUE TITLE
Switch from serializing podcasts and saving them as a JSON in the local storage folder to a database using EntityFramework with SQLite

### ISSUE THREAD

**Issue by robertiagar** [Solocast/solocast-clients#17]
See EF 7 [documentation](https://ef.readthedocs.io/en/latest/)

**Comment by jeromechrist** [comment]
Hey,

Willing to help you on this one.

**Comment by robertiagar** [comment]
Sure thing. Not sure how well it's documented for UWP, but you can try taking a look [here](https://docs.efproject.net/en/latest/).

**Comment by robertiagar** [comment]
Getting started with UWP: https://docs.efproject.net/en/latest/platforms/uwp/index.html

**Comment by jeromechrist** [comment]
Yep, was going to follow this.

From what i see in the project implementing ILocalStorageService would be enough (and maybe renaming the interface to support both storage methods).

One question though : do you want to store the same way (blob like) or relational with tables ?

Also would you mind adding hacktoberfest label ? :blush:

**Comment by robertiagar** [comment]
I think having it relational would help us in the long run :)

You can rename to be a little more generic. Can't wait to see what you come up with :)

**Comment by robertiagar** [comment]
@jeromechrist do you mind If I create the pull request? I will be easier to track your changes like that, rather than reviewing the whole thing at the end.

**Comment by jeromechrist** [comment]
@robertiagar sure go ahead, i just finished a few minutes ago.

I've added the corresponding unit test, passing 

![image](https://cloud.githubusercontent.com/assets/2547646/19677506/f0cfd9ee-9a99-11e6-85a9-3e8ca550c42d.png)

You can still go back to using LocalStorage, injecting the service in simple IoC still works like previously.

A few noteworthy details :
- I had to change Uri types to string from Podcast & Episode entity because EF couldn't figure out how to store it (which is understandable since it's a complex type).  I think it's achieveable through the InitialMigration Migration class if you specifies the mapping to be a string but it adds complexity / hide the concrete DataModel from just looking at the entities.
- I've added relations between Podcast / Episode with navigation properties and Ids used by convention by EF (see PodcastId & EpisodeId)
- Migrations are applied when AppShell is instanciated : not sure if it's the best place, typically we put that kind of logic inside the bootstrapper of the App

an exemple of what is store inside the SQLite database :

![image](https://cloud.githubusercontent.com/assets/2547646/19677934/f60e6748-9a9b-11e6-881e-59847cfdf586.png)

![image](https://cloud.githubusercontent.com/assets/2547646/19677952/08311772-9a9c-11e6-99ff-08a806e9e8eb.png)

Let me know if you need some changes.

**Comment by jeromechrist** [comment]
I can do a squash commit if you'd like to see all the changes in 1 commit.

**Comment by robertiagar** [comment]
Created the pull request and left 1 comment, did you get it?

**Comment by jeromechrist** [comment]
@robertiagar yes, done !

**Comment by robertiagar** [comment]
@jeromechrist thanks for the help, I merged it. There are a few more issues, that are open if you're willing to help out :)
